global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend"
    dns_sd_configs:
      - names:
          - "backend"
        type: A
        port: 5000

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
